name: globaluy_test_app
description: GlobalUY.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  flutter_dotenv: ^5.0.2
  shimmer: ^2.0.0
  http: ^0.13.5
  flutter_svg: ^1.1.6
  google_sign_in: ^5.4.2
  json_annotation: ^4.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.8
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
flutter:
  uses-material-design: true
  assets:
    - lib/resources/images/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Light.ttf
        # - asset: fonts/Poppins/Poppins-Medium.ttf
        #   weight: 400
        - asset: fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
